
service: modular-example

plugins:
  - serverless-plugin-modularize

custom:
  modularize:
    glob: 'src/**/*.module.yml'

package:
  individually: true
  excludeDevDependencies: false
  exclude:
   - node_modules/**

provider:
  name: aws
  region: us-east-1
  runtime: nodejs16.x
  logRetentionInDays: 1
  timeout: 30
  memorySize: 1536